server.port=8081

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# user-service base URL for inter-service calls
user.service.baseUrl=${USER_SERVICE_URL:http://127.0.0.1:8080}